<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий на hh.ru

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly
import plotly.express as px
import seaborn as sns
from plotly.subplots import make_subplots

# Исследование структуры данных

1. Прочитайте данные с помощью библиотеки Pandas. Совет: перед чтением обратите внимание на разделитель внутри файла.

In [2]:
hh_data = pd.read_csv('dst-3.0_16_1_hh_database.csv', sep =';')

2. Выведите несколько первых (последних строк таблицы), чтобы убедиться в том, что ваши данные не повреждены. Ознакомьтесь с признаками и их структурой.

In [7]:
hh_data.head()

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,Не указано
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,Не указано

3. Выведите основную информацию о числе непустых значений в столбцах и их типах в таблице

4. Обратите внимание на информацию о числе непустых значений

In [8]:
hh_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44744 entries, 0 to 44743
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Пол, возраст                     44744 non-null  object
 1   ЗП                               44744 non-null  object
 2   Ищет работу на должность:        44744 non-null  object
 3   Город, переезд, командировки     44744 non-null  object
 4   Занятость                        44744 non-null  object
 5   График                           44744 non-null  object
 6   Опыт работы                      44576 non-null  object
 7   Последнее/нынешнее место работы  44743 non-null  object
 8   Последняя/нынешняя должность     44742 non-null  object
 9   Образование и ВУЗ                44744 non-null  object
 10  Обновление резюме                44744 non-null  object
 11  Авто                             44744 non-null  object
dtypes: object(12)
memory usage: 4.1+ MB

5. Выведите основную статистическую информацию о столбцах.

In [9]:
hh_data.describe()

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
count,44744,44744,44744,44744,44744,44744,44576,44743,44742,44744,44744,44744
unique,16003,690,14929,10063,38,47,44413,30214,16927,40148,18838,2
top,"Мужчина , 32 года , родился 17 сентября 1986",50000 руб.,Системный администратор,"Москва , не готов к переезду , не готов к кома...",полная занятость,полный день,Опыт работы 10 лет 8 месяцев Апрель 2018 — по...,Индивидуальное предпринимательство / частная п...,Системный администратор,Высшее образование 2014 Московский технически...,07.05.2019 09:50,Не указано
freq,18,4064,3099,1261,30026,22727,3,935,2062,4,25,32268

# Преобразование данных

1. Начнем с простого - с признака **"Образование и ВУЗ"**. Его текущий формат это: **<Уровень образования год выпуска ВУЗ специальность...>**. Например:
* Высшее образование 2016 Московский авиационный институт (национальный исследовательский университет)...
* Неоконченное высшее образование 2000  Балтийская государственная академия рыбопромыслового флота…
Нас будет интересовать только уровень образования.

Создайте с помощью функции-преобразования новый признак **"Образование"**, который должен иметь 4 категории: "высшее", "неоконченное высшее", "среднее специальное" и "среднее".

Выполните преобразование, ответьте на контрольные вопросы и удалите признак "Образование и ВУЗ".

Совет: обратите внимание на структуру текста в столбце **"Образование и ВУЗ"**. Гарантируется, что текущий уровень образования соискателя всегда находится в первых 2ух слов и начинается с заглавной буквы. Воспользуйтесь этим.

*Совет: проверяйте полученные категории, например, с помощью метода unique()*

In [10]:
def get_education (education):
    education_list = education.split(' ')
    education_short_list = education_list[:2]
    if education_short_list[0] == "Высшее":
        education_type = "высшее"
    elif education_short_list[0] == "Неоконченное":
        education_type = "неоконченное высшее"
    elif education_short_list[0] == "Среднее":
        if education_short_list[1] == "специальное":
            education_type = "среднее специальное"
        else:
            education_type = "среднее"
    return education_type

hh_data['Образование'] = hh_data['Образование и ВУЗ'].apply(get_education)
hh_data[hh_data['Образование'] == 'среднее'].shape[0]
hh_data.drop("Образование и ВУЗ", axis = 1, inplace = True)

2. Теперь нас интересует столбец **"Пол/возраст"**. Сейчас он представлен в формате **<Пол , возраст , дата рождения >**. Например:
* Мужчина , 39 лет , родился 27 ноября 1979 
* Женщина , 21 год , родилась 13 января 2000
Как вы понимаете, нам необходимо выделить каждый параметр в отдельный столбец.

Создайте два новых признака **"Пол"** и **"Возраст"**. При этом важно учесть:
* Признак пола должен иметь 2 уникальных строковых значения: 'М' - мужчина, 'Ж' - женщина. 
* Признак возраста должен быть представлен целыми числами.

Выполните преобразование, ответьте на контрольные вопросы и удалите признак **"Пол, возраст"** из таблицы.

*Совет: обратите внимание на структуру текста в столбце, в части на то, как разделены параметры пола, возраста и даты рождения между собой - символом ' , '. 
Гарантируется, что структура одинакова для всех строк в таблице. Вы можете воспользоваться этим.*

In [ ]:
def get_gender (sex):
    sex_list = sex.split(' , ')
    sex_short_list = sex_list[:1]
    if sex_short_list[0] == "Мужчина":
        sex_type = "М"
    else:
        sex_type = "Ж"
    return sex_type
def get_age (age):
    age_list = age.split(' , ')
    age_short_list = age_list[1]
    age_short_list_new = age_short_list.split(' ')
    age_number = age_short_list_new[1]
    return age_number
hh_data['Пол'] = hh_data['Пол, возраст'].apply(get_gender)
hh_data['Возраст'] = hh_data['Пол, возраст'].apply(get_age)
round(hh_data['Пол'].value_counts(normalize=True)*100,2)
hh_data['Возраст'] = hh_data['Возраст'].astype('int')
round(hh_data['Возраст'].mean(),1)
hh_data.drop("Пол, возраст", axis = 1, inplace = True)

3. Следующим этапом преобразуем признак **"Опыт работы"**. Его текущий формат это: **<Опыт работы: n лет m месяцев, периоды работы в различных компаниях…>**. 

Из столбца нам необходимо выделить общий опыт работы соискателя в месяцах, новый признак назовем "Опыт работы (месяц)"

Для начала обсудим условия решения задачи:
* Во-первых, в данном признаке есть пропуски. Условимся, что если мы встречаем пропуск, оставляем его как есть (функция-преобразование возвращает NaN)
* Во-вторых, нас не интересует информация, которая описывается после указания опыта работы (периоды работы в различных компаниях)
* В-третьих, у нас есть проблема: опыт работы может быть представлен только в годах или только месяцах. Например, можно встретить следующие варианты:
    * Опыт работы 3 года 2 месяца…
    * Опыт работы 4 года…
    * Опыт работы 11 месяцев…
Учитывайте эту особенность в вашем коде

В результате преобразования у вас должен получиться столбец, содержащий информацию о том, сколько месяцев проработал соискатель.
Выполните преобразование, ответьте на контрольные вопросы и удалите столбец **"Опыт работы"** из таблицы.

In [ ]:
def get_experience(experience):
    months_keywords = ['месяц','месяца','месяцев']
    years_keywords = ['года','лет','год']
    month = 0
    year = 0
    if experience is not np.nan:
        exp_split = experience.split(' ')
        exp_split_new = exp_split[:7]
        for i in range(len(exp_split_new)):
            if exp_split_new[i] in months_keywords:
                month = exp_split_new[i-1]
            if exp_split_new[i] in years_keywords:
                year = exp_split_new[i-1]
        return int(year)*12+int(month)
    else:
        return np.nan  
hh_data['Опыт работы (месяц)'] = hh_data['Опыт работы'].apply(get_experience)
hh_data['Опыт работы (месяц)'].median()
hh_data.drop("Опыт работы", axis = 1, inplace = True)

4. Хорошо идем! Следующий на очереди признак "Город, переезд, командировки". Информация в нем представлена в следующем виде: **<Город , (метро) , готовность к переезду (города для переезда) , готовность к командировкам>**. В скобках указаны необязательные параметры строки. Например, можно встретить следующие варианты:

* Москва , не готов к переезду , готов к командировкам
* Москва , м. Беломорская , не готов к переезду, не готов к командировкам
* Воронеж , готов к переезду (Сочи, Москва, Санкт-Петербург) , готов к командировкам

Создадим отдельные признаки **"Город"**, **"Готовность к переезду"**, **"Готовность к командировкам"**. При этом важно учесть:

* Признак **"Город"** должен содержать только 4 категории: "Москва", "Санкт-Петербург" и "город миллионник" (их список ниже), остальные обозначьте как "другие".

    Список городов миллионников:
    
   <code> million_cities = ['Новосибирск', 'Екатеринбург','Нижний Новгород','Казань', 'Челябинск','Омск', 'Самара', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 'Воронеж','Волгоград']
    </code>
    
    
    Инфорация о метро, рядом с которым проживает соискатель нас не интересует.
* Признак **"Готовность к переезду"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к переезду в признаке "Город, переезд, командировки". Например:
    * … , готов к переезду , …
    * … , не готова к переезду , …
    * … , готова к переезду (Москва, Санкт-Петербург, Ростов-на-Дону)
    * … , хочу переехать (США) , …
    
    Нас интересует только сам факт возможности или желания переезда.
* Признак **"Готовность к командировкам"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к командировкам в признаке "Город, переезд, командировки". Например:
    * … , готов к командировкам , … 
    * … , готова к редким командировкам , …
    * … , не готов к командировкам , …
    
    Нас интересует только сам факт готовности к командировке.
    
Выполните преобразования и удалите столбец **"Город, переезд, командировки"** из таблицы.

*Совет: обратите внимание на то, что структура текста может меняться в зависимости от указания ближайшего метро. Учите это, если будете использовать порядок слов в своей программе.*

In [6]:
#определение города
def get_city (city):
    million_cities = ['Сочи','Москва','Санкт-Петербург','Новосибирск', 'Екатеринбург', 'Нижний Новгород', 'Казань', 'Челябинск', 'Омск',
                      'Самара', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 'Воронеж', 'Волгоград' ]
    full_list = city.split(' , ')
    city = full_list[0]
    if city not in million_cities:
        city = 'другие'
    return city
hh_data['Город'] = hh_data['Город, переезд, командировки'].apply(get_city)

#определение готовности к перезду
def get_move_status (moving):
    ready_keywords = ['готов','готова','хочу']
    move_split = moving.split(' , ')
    if len(move_split) == 4:
        move_status = move_split[2]
    else:
        move_status = move_split[1]
    move_status_split = move_status.split(' ')
    for i in range(len(move_status_split)):
        if move_status_split[i] in ready_keywords:
            if move_status_split[i-1] == 'не':
                return False
            else:
                return True
        else:
            return False
hh_data['Готовность к переезду'] = hh_data['Город, переезд, командировки'].apply(get_move_status)

#определение готовности к командировке
def get_business_trip_status (trip):
    ready_keywords = ['готов','готова']
    trip_split = trip.split(' , ')
    if len(trip_split) == 4:
        trip_status = trip_split[3]
    elif len(trip_split) == 3:
        trip_status = trip_split[2]
    elif len(trip_split) == 5:
        trip_status = trip_split[4]
    else:
        trip_status = '' 
    if trip_status is '':
        return False
    else:
        trip_status_split = trip_status.split(' ')
        for i in range(len(trip_status_split)):
            if trip_status_split[i] in ready_keywords:
                if trip_status_split[i-1] == 'не':
                    return False
                else:
                    return True
            else:
                return False
hh_data['Готовность к командировкам'] = hh_data['Город, переезд, командировки'].apply(get_business_trip_status)

#выполнение заданий
round(hh_data[hh_data['Город'] == "Санкт-Петербург"].shape[0]/hh_data.shape[0]*100,0)
round(hh_data[(hh_data['Готовность к командировкам'] == True) & (hh_data['Готовность к переезду'] == True)].shape[0]/hh_data.shape[0]*100,0)

#удаление столбца "Город, переезд, командировки" 
hh_data.drop("Город, переезд, командировки", axis = 1, inplace = True)

5. Рассмотрим поближе признаки **"Занятость"** и **"График"**. Сейчас признаки представляют собой набор категорий желаемой занятости (полная занятость, частичная занятость, проектная работа, волонтерство, стажировка) и желаемого графика работы (полный день, сменный график, гибкий график, удаленная работа, вахтовый метод).
На сайте hh.ru соискатель может указывать различные комбинации данных категорий, например:
* полная занятость, частичная занятость
* частичная занятость, проектная работа, волонтерство
* полный день, удаленная работа
* вахтовый метод, гибкий график, удаленная работа, полная занятость

Такой вариант признаков имеет множество различных комбинаций, а значит множество уникальных значений, что мешает анализу. Нужно это исправить!

Давайте создадим признаки-мигалки для каждой категории: если категория присутствует в списке желаемых соискателем, то в столбце на месте строки рассматриваемого соискателя ставится True, иначе - False.

Такой метод преобразования категориальных признаков называется One Hot Encoding и его схема представлена на рисунке ниже:
<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/ohe.jpg>
Выполните данное преобразование для признаков "Занятость" и "График", ответьте на контрольные вопросы, после чего удалите их из таблицы

In [ ]:
def get_split_occupation_schedule (occupation):
    occupation_split = occupation.split(', ')
    return occupation_split

hh_data['Занятость'] = hh_data['Занятость'].apply(get_split_occupation_schedule)
hh_data['полная занятость'] = hh_data['Занятость'].apply(lambda x:'полная занятость' in x)
hh_data['частичная занятость'] = hh_data['Занятость'].apply(lambda x:'частичная занятость' in x)
hh_data['проектная работа'] = hh_data['Занятость'].apply(lambda x:'проектная работа' in x)
hh_data['стажировка'] = hh_data['Занятость'].apply(lambda x:'стажировка' in x)
hh_data['волонтерство'] = hh_data['Занятость'].apply(lambda x:'волонтерство' in x)

hh_data['График'] = hh_data['График'].apply(get_split_occupation_schedule)
hh_data['полный день'] = hh_data['График'].apply(lambda x:'полный день' in x)
hh_data['сменный график'] = hh_data['График'].apply(lambda x:'сменный график' in x)
hh_data['гибкий график'] = hh_data['График'].apply(lambda x:'гибкий график' in x)
hh_data['удаленная работа'] = hh_data['График'].apply(lambda x:'удаленная работа' in x)
hh_data['вахтовый метод'] = hh_data['График'].apply(lambda x:'вахтовый метод' in x)

#выполнение задания
hh_data[(hh_data['проектная работа'] == True) & (hh_data['волонтерство'] == True)].shape[0]
hh_data[(hh_data['вахтовый метод'] == True) & (hh_data['гибкий график'] == True)].shape[0]

#удаление столбцов
hh_data.drop("Занятость", axis = 1, inplace = True)
hh_data.drop("График", axis = 1, inplace = True)

6. (2 балла) Наконец, мы добрались до самого главного и самого важного - признака заработной платы **"ЗП"**. 
В чем наша беда? В том, что помимо желаемой заработной платы соискатель указывает валюту, в которой он бы хотел ее получать, например:
* 30000 руб.
* 50000 грн.
* 550 USD

Нам бы хотелось видеть заработную плату в единой валюте, например, в рублях. Возникает вопрос, а где взять курс валют по отношению к рублю?

На самом деле язык Python имеет в арсенале огромное количество возможностей получения данной информации, от обращения к API Центробанка, до использования специальных библиотек, например pycbrf. Однако, это не тема нашего проекта.

Поэтому мы пойдем в лоб: обратимся к специальным интернет-ресурсам для получения данных о курсе в виде текстовых файлов. Например, MDF.RU, данный ресурс позволяет удобно экспортировать данные о курсах различных валют и акций за указанные периоды в виде csv файлов. Мы уже сделали выгрузку курсов валют, которые встречаются в наших данных за период с 29.12.2017 по 05.12.2019. Скачать ее вы можете **на платформе**

Создайте новый DataFrame из полученного файла. В полученной таблице нас будут интересовать столбцы:
* "currency" - наименование валюты в ISO кодировке,
* "date" - дата, 
* "proportion" - пропорция, 
* "close" - цена закрытия (последний зафиксированный курс валюты на указанный день).


Перед вами таблица соответствия наименований иностранных валют в наших данных и их общепринятых сокращений, которые представлены в нашем файле с курсами валют. Пропорция - это число, за сколько единиц валюты указан курс в таблице с курсами. Например, для казахстанского тенге курс на 20.08.2019 составляет 17.197 руб. за 100 тенге, тогда итоговый курс равен - 17.197 / 100 = 0.17197 руб за 1 тенге.
Воспользуйтесь этой информацией в ваших преобразованиях.

<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/table.jpg>


Осталось только понять, откуда брать дату, по которой определяется курс? А вот же она - в признаке **"Обновление резюме"**, в нем содержится дата и время, когда соискатель выложил текущий вариант своего резюме. Нас интересует только дата, по ней бы и будем сопоставлять курсы валют.

Теперь у нас есть вся необходимая информация для того, чтобы создать признак "ЗП (руб)" - заработная плата в рублях.

После ответа на контрольные вопросы удалите исходный столбец заработной платы "ЗП" и все промежуточные столбцы, если вы их создавали.

Итак, давайте обсудим возможный алгоритм преобразования: 
1. Перевести признак "Обновление резюме" из таблицы с резюме в формат datetime и достать из него дату. В тот же формат привести признак "date" из таблицы с валютами.
2. Выделить из столбца "ЗП" сумму желаемой заработной платы и наименование валюты, в которой она исчисляется. Наименование валюты перевести в стандарт ISO согласно с таблицей выше.
3. Присоединить к таблице с резюме таблицу с курсами по столбцам с датой и названием валюты (подумайте, какой тип объединения надо выбрать, чтобы в таблице с резюме сохранились данные о заработной плате, изначально представленной в рублях). Значение close для рубля заполнить единицей 1 (курс рубля самого к себе)
4. Умножить сумму желаемой заработной платы на присоединенный курс валюты (close) и разделить на пропорцию (обратите внимание на пропуски после объединения в этих столбцах), результат занести в новый столбец "ЗП (руб)".

In [ ]:
#получение необходимого dataframe для конвертирования валют
exchange_rates = pd.read_csv('ExchangeRates_Project_1.ipynb')
exchange_rates["date"] = pd.to_datetime(exchange_rates["date"])
exchange_rates_df = exchange_rates[['currency','date','proportion','close']]
exchange_rates_df['date'] = exchange_rates_df['date'].dt.date

#функции для получения валюты и зарплаты (только число)
def get_currency(salary):
    salary_split = salary.split(' ')
    currency = salary_split[1]
    return currency
def get_salary_number (salary):
    salary_split = salary.split(' ')
    salary_number = salary_split[0]
    return salary_number

#приведение столбцов к необходимому формату
hh_data['Обновление резюме'] = pd.to_datetime(hh_data['Обновление резюме'])
hh_data['date'] = hh_data['Обновление резюме'].dt.date
hh_data['currency'] = hh_data['ЗП'].apply(get_currency)
hh_data.loc[hh_data['currency'] == 'грн.','currency'] = 'UAH'
hh_data.loc[hh_data['currency'] == 'бел.руб.','currency'] = 'BYN'
hh_data.loc[hh_data['currency'] == 'сум','currency'] = 'UZS'

#объединение таблиц
hh_data_merged = hh_data.merge(
    exchange_rates_df,
    on=['currency','date'],
    how='left'
)

hh_data_merged.loc[hh_data_merged['currency'] == 'руб.','proportion'] = 1
hh_data_merged.loc[hh_data_merged['currency'] == 'руб.','close'] = 1

hh_data_merged['ЗП (руб)'] = hh_data_merged['ЗП'].apply(get_salary_number)
hh_data_merged['ЗП (руб)'] = hh_data_merged['ЗП (руб)'].astype('int64')
hh_data_merged['ЗП (руб)'] = hh_data_merged['ЗП (руб)'] * hh_data_merged.close / hh_data_merged.proportion

#выполнение задания
hh_data_merged['ЗП (руб)'].median()

#удаление столбца ЗП
hh_data_merged.drop("ЗП", axis = 1, inplace = True)

# Исследование зависимостей в данных

1. Постройте распределение признака **"Возраст"**. Опишите распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится возраст большинства соискателей? Есть ли аномалии для признака возраста, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [11]:
fig = px.histogram(
    data_frame=hh_data_merged,
    x='Возраст',
    title='Распределение возраста соискателей',
    marginal='box'
)
fig.show()

В результате анализа возраста получили распределение слегка асимметричное в левую сторону. Модальное значение находится около значения возраста 30 лет (более 2800 соискателей). Возраст всех соискателей находится в пределах от 14 до 100 лет. Возраст большинства соискателей находится примерно в пределах от 25 до 37 лет. Согласно графику, очень сильно выбивается значение возраста в 100 лет, а также под "подозрение" попадают значения возраста после 50 лет.

2. Постройте распределение признака **"Опыт работы (месяц)"**. Опишите данное распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится опыт работы большинства соискателей? Есть ли аномалии для признака возраста, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [ ]:
fig = px.histogram(
    data_frame=hh_data_merged,
    x='Опыт работы (месяц)',
    title='Распределение опыта работы соискателей',
    marginal='box'
)
fig.show()

Аналогично распределению возраста, получили распределение слегка асимметричное в левую сторону. Модальное значение находится около значения опыта работы 81 месяц (около 1400 соискателей). Опыт работы всех соискателей находится в пределах от 0 до 1200 месяцев. Опыт работы большинства соискателей находится примерно в пределах от 25 до 145 месяцев. Согласно графику, очень сильно выбивается значение опыта работы в 1200 месяцев (100 лет), а также под "подозрение" попадают значения опыта работы после 300 месяцев.

3. Постройте распределение признака **"ЗП (руб)"**. Опишите данное распределение, отвечая на следующие вопросы: каковы предельные значения признака, в каком примерном интервале находится заработная плата большинства соискателей? Есть ли аномалии для признака возраста? Обратите внимание на гигантские размеры желаемой заработной платы.
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [ ]:
fig = px.histogram(
    data_frame=hh_data_merged,
    x='ЗП (руб)',
    title='Распределение ожидаемой зарплаты соискателей',
    marginal='box'
)
fig.show()

Согласно графику, распределение ожидаемой зарплаты соискателей напоминает логнормальное распределение. Это связано с тем, что у пяти сосискателей ожидаемая зарплата превышает более 1000000 рублей (а у 1 сосикателя она составялет 25 миллионов, что скорее всего требует тщательной проверки), при этом модальное значение составляет 50000 рублей. Ожидаемая зарплата в общем находится в пределах от 1 (что тоже попадает под подозрение) до 25 миллионов рублей, а ожидаемая зарплата большинства соискателей находится в пределах от 38 тыс. до 95 тыс. рублей.

4. Постройте диаграмму, которая показывает зависимость **медианной** желаемой заработной платы (**"ЗП (руб)"**) от уровня образования (**"Образование"**). Используйте для диаграммы данные о резюме, где желаемая заработная плата меньше 1 млн рублей.
*Сделайте выводы по представленной диаграмме: для каких уровней образования наблюдаются наибольшие и наименьшие уровни желаемой заработной платы? Как вы считаете, важен ли признак уровня образования при прогнозировании заработной платы?*

In [ ]:
hh_data_merged_less = hh_data_merged[hh_data_merged['ЗП (руб)'] < 1000000]
education_salary_median = hh_data_merged_less.groupby('Образование',as_index = False)[['ЗП (руб)']].median()

fig = plt.figure(figsize=(10, 6))
barplot = sns.barplot(
    data=education_salary_median,
    x='Образование',
    y='ЗП (руб)'
)
barplot.set_title("Зависимость медианной желаемой заработной платы от уровня образования")

Согласно получившейся диаграмме, мы видим прямую зависимость уровня образования от ожидаемой зарплаты - чем выше образование, тем выше ожидаемая медианная зарплата соискателей. Наибольшая зарплата наблюдается для сосискателей с высшим и неоконченным высшим образованием, а наименьшая - для соискателей со средним и средним специальным образованием. Мне кажется, что признак уровня образования является важным признаком при прогнозировании заработной платы, так как, во-первых, есть четкая зависимость по днным HeadHunter, а во-вторых, уровень образования показывает квалификацию соискателя, о его возможных навыках быстро разобраться в новой области, его возможностях, но мне кажется, лучше использовать этот признак вместе с учреждением, который окончил соискатель. Так как среди институтов/университетов, возможно, тодже есть связь с качеством образования.

5. Постройте диаграмму, которая показывает распределение желаемой заработной платы (**"ЗП (руб)"**) в зависимости от города (**"Город"**). Используйте для диаграммы данные о резюме, где желая заработная плата меньше 1 млн рублей.
*Сделайте выводы по полученной диаграмме: как соотносятся медианные уровни желаемой заработной платы и их размах в городах? Как вы считаете, важен ли признак города при прогнозировании заработной платы?*

In [ ]:
fig = px.box(
    data_frame=hh_data_merged_less, 
    x="Город", 
    y="ЗП (руб)", 
    color='Город',  
    orientation='v',
    title='Зависимость желаемой заработной платы от города' 
)
fig.show()

Согласно графику, можно выделить три группы городов в зависимости от медианной желаемой заработной платы. В первую группу входит Москва и Санкт-Петербург, чья медианная зарплата составляет более 60 тыс. рублей, и имеющие наибольший рахмах в заработной плате. Во вторую группу входят Новосибирск, Сочи и Екатеринбург, чья ожидаемая медианная заработная плата составляет около 50 тыс. рублей. И в третью группу входят оставшиеся города, так как их медианная зарплата составляет около 40 тыс. рублей. Мне кажется, что город тоже необходимо при прогнозировании заработной платы, так как все крупные города (регионы) имеют разную экономическую ситуацию, разные промышленные объекты и разную населенность.

6. Постройте **многоуровневую столбчатую диаграмму**, которая показывает зависимость медианной заработной платы (**"ЗП (руб)"**) от признаков **"Готовность к переезду"** и **"Готовность к командировкам"**. Проанализируйте график, сравнив уровень заработной платы в категориях.

In [1]:
bar_data = hh_data_merged.groupby(['Готовность к переезду','Готовность к командировкам'], as_index=False)[['ЗП (руб)']].median()

fig = px.bar(
    data_frame=bar_data,
    y='Готовность к переезду',
    x='ЗП (руб)',
    barmode="group",
    color='Готовность к командировкам',
    orientation='h',
    title='Медианная з/п по готовности к командировкам и переездам'
)

#отображаем график
fig.show()

NameError: name 'hh_data_merged' is not defined

Наибольшая заработная плата наблюдается среди соискателей готовых к переезду по сравнению с теми, кто  не готов, не учитывая 
их готовность к командировкам. А те сосикатели, которые готовы и к командировкам и к переездам, имеют наивысшую ожидаемую
заработную плату. Соответственно, среди тех соискателей, которые не готовы ни к командировкам, ни к перездам, имеют 
наименьшую заработную плату

7. Постройте сводную таблицу, иллюстрирующую зависимость **медианной** желаемой заработной платы от возраста (**"Возраст"**) и образования (**"Образование"**). На полученной сводной таблице постройте **тепловую карту**. Проанализируйте тепловую карту, сравнив показатели внутри групп.

In [ ]:
pivot_data = hh_data_merged.pivot_table(
    values='ЗП (руб)',
    index='Образование',
    columns='Возраст',
    aggfunc='median',
    fill_value=0
)

heatmap = px.imshow(pivot_data, title='Медианная зарплата в зависимости от образования и возраста')
heatmap.show()

Среди соискателей с высшим образованием наблюдается очень завышенная заработная плата до 20 лет (варьируется в пределах 80-120 тыс), а уже после 20 лет наблюдается увеличение зарплаты с увеличением возраста. Среди сосикателей с неоконченным высшим образованием, наблюдается ожидаемая зарплата в примерно 80 тыс рублей среди кандидатов до 20 лет, а после 20 лет наблюдается линейная зависимость ожидаемой зарплаты от возраста. Среди сосикателей со средним и средним специальным образованием наблюдается увеличение ожидаемой заработной платы с увеличением возраста, но диапазон ниже, чем для соискателей с более высшим образованием.

8. Постройте **диаграмму рассеяния**, показывающую зависимость опыта работы (**"Опыт работы (месяц)"**) от возраста (**"Возраст"**). Опыт работы переведите из месяцев в года, чтобы признаки были в едином масштабе. Постройте на графике дополнительно прямую, проходящую через точки (0, 0) и (100, 100). Данная прямая соответствует значениям, когда опыт работы равен возрасту человека. Точки, лежащие на этой прямой и выше нее - аномалии в наших данных (опыт работы больше либо равен возрасту соискателя)

In [ ]:
hh_data_merged['Опыт работы (годы)'] = hh_data_merged['Опыт работы (месяц)'] / 12

fig = plt.figure(figsize=(10, 5))
sns.lineplot(x=[0, 100], y=[0, 100])
ax = sns.scatterplot(
    data=hh_data_merged, 
    x='Возраст',
    y='Опыт работы (годы)',
)
ax.set_title('Зависимость опыта работы от возраста')

Наблюдается прямая зависимость возраста с опытом работы - чем взрослее соискатель, тем соотвественно, у него больше опыт. Наблюдается несколько выбросов, на которые необходимо посмотреть более пристально. Так, например, есть соискатели, чей опыт работы превышает возраст.

**Дополнительные баллы**

Для получения 2 дополнительных баллов по разведывательному анализу постройте еще два любых содержательных графика или диаграммы, которые помогут проиллюстрировать влияние признаков/взаимосвязь между признаками/распределения признаков. Приведите выводы по ним. Желательно, чтобы в анализе участвовали признаки, которые мы создавали ранее в разделе "Преобразование данных".

In [ ]:
fig = plt.figure(figsize=(10, 7))
boxplot = sns.boxplot(
    data=hh_data_merged_less,
    y='ЗП (руб)',
    x='Пол',
    width=0.9
)
boxplot.set_title('Распределение ожидаемой заработной платы по полу');
boxplot.set_xlabel('Пол');
boxplot.set_ylabel('Ожидаемая заработная плата');
boxplot.grid()

Согласно графику, медианная заработная платана среди женщин немного ниже, чем для мужчин, и размах зарплат для мужчин намного шире, чем для женщин. Мне кажется, что пол необходимо тоже будет необходимо включить, как важный признак при прогнозировании зарплат

In [ ]:
hh_data_merged_less['Опыт работы (годы)'] = hh_data_merged_less['Опыт работы (месяц)'] / 12

fig = plt.figure(figsize=(10, 5))
#sns.lineplot(x=[0, 100], y=[0, 100])
plot = sns.scatterplot(
    data=hh_data_merged_less, 
    y='ЗП (руб)',
    x='Опыт работы (годы)',
    hue='Пол'
)
ax.set_title('Зависимость опыта работы от ожидаемой заработной платы')

Не наблюдается четкой зависимости между от опыта работы и заработной платы, хотя было бы логично, что чем выше опыт работы, то тем выше заработная плата.

# Очистка данных

1. Начнем с дубликатов в наших данных. Найдите **полные дубликаты** в таблице с резюме и удалите их.

In [ ]:
duplicates = hh_data_merged[hh_data_merged.duplicated(subset=hh_data_merged.columns)]
hh_data_merged = hh_data_merged.drop_duplicates()
duplicates.shape[0]

2. Займемся пропусками. Выведите информацию **о числе пропусков** в столбцах.

In [ ]:
null_data = hh_data_merged.isnull().sum()
null_data[null_data > 0]

3. Итак, у нас есть пропуски в 3ех столбцах: **"Опыт работы (месяц)"**, **"Последнее/нынешнее место работы"**, **"Последняя/нынешняя должность"**. Поступим следующим образом: удалите строки, где есть пропуск в столбцах с местом работы и должностью. Пропуски в столбце с опытом работы заполните **медианным** значением.

In [ ]:
hh_data_merged = hh_data_merged.dropna(subset=['Последнее/нынешнее место работы', 'Последняя/нынешняя должность'])
values = {
    'Опыт работы (месяц)': hh_data_merged['Опыт работы (месяц)'].median()
}
hh_data_merged = hh_data_merged.fillna(values)

round(hh_data_merged['Опыт работы (месяц)'].mean(),2)

4. Мы добрались до ликвидации выбросов. Сначала очистим данные вручную. Удалите резюме, в которых указана заработная плата либо выше 1 млн. рублей, либо ниже 1 тыс. рублей.

In [ ]:
outliers1 = hh_data_merged[(hh_data_merged['ЗП (руб)'] > 1000000) | (hh_data_merged['ЗП (руб)'] < 1000)]
hh_data_merged = hh_data_merged.drop(outliers1.index)
outliers1.shape[0]

5. В процессе разведывательного анализа мы обнаружили резюме, в которых **опыт работы в годах превышал возраст соискателя**. Найдите такие резюме и удалите их из данных

In [12]:
outliers2 = hh_data_merged[hh_data_merged['Опыт работы (годы)'] >= hh_data_merged['Возраст']]
hh_data_merged = hh_data_merged.drop(outliers2.index)
outliers2.shape[0]

6. В результате анализа мы обнаружили потенциальные выбросы в признаке **"Возраст"**. Это оказались резюме людей чересчур преклонного возраста для поиска работы. Попробуйте построить распределение признака в **логарифмическом масштабе**? В какую сторону **асимметрично логарифмическое распределение**? Найдите выбросы с помощью **метода z-отклонения** и удалите их из данных, используйте логарифмический масштаб, сделайте **послабление на 1 сигму (возьмите 4 сигмы)** в сторону, противоположную асимметрии.

In [ ]:
#гистограмма в логарифмическом масштабе
log_age= np.log(hh_data_merged['Возраст'])
histplot = sns.histplot(log_age , bins=30)
histplot.set_title('Распределение возраста в логарифмическом масштабе');

#логарифмическое рапределение асимметрично слегка влево

def outliers_z_score_mod(data, feature, log_scale=False,left=3,right=3):
    if log_scale:
        x = np.log(data[feature])
    else:
        x = data[feature]
    mu = x.mean()
    sigma = x.std()
    lower_bound = mu - left * sigma
    upper_bound = mu + right * sigma
    outliers = data[(x < lower_bound) | (x > upper_bound)]
    cleaned = data[(x > lower_bound) & (x < upper_bound)]
    return outliers, cleaned

outliers, cleaned = outliers_z_score_mod(hh_data_merged, 'Возраст', log_scale=True,left=3,right=4)
print(f'Число выбросов по методу z-отклонения: {outliers.shape[0]}')